---
- name: Check skrull dir exists
  file:
    dest: ~/skrull
    state: directory
- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: ~/skrull/docker-compose.yml

- name: Copy prometheus.yml
  copy:
    src: prometheus.yml
    dest: ~/skrull

- name: Create node scrape config
  template:
    src: node_scrape_configs.yml.j2
    dest: ~/skrull/node_scrape_configs.yml

- name: Create run.sh
  template:
    src: run.sh.j2
    dest: ~/skrull/run.sh
    mode: +x
