---
- name: hostname
  hostname:
    name: "{{inventory_hostname}}"
  become: true

- name: Add IP address of all hosts to all hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"