---
# docker_registry: eu.gcr.io/disappointing-tode
docker_registry: master:5000

docker_images:
  skrull: 
    tag: 5c118e12fc.dirty
  fnanny:
    tag: 143d01256c.dirty
  prometheus: 
    tag: 11fe61decd
  node-exporter:
    tag: latest

gcloud_docker: "{{ docker_registry is match(\".*.gcr.io\")}}"

swarm_iface: eth0 # Cloud
#swarm_iface: em1 # Hardware
