---
- file:
    dest: ~/project
    state: directory
- name: Extract project
  unarchive:
    src: project.tar.gz
    dest: ~/project
- copy:
    src: docker-compose.yml
    dest: ~/project
- copy:
    src: .env
    dest: ~/project

- file:
    dest: ~/project/build/assembly/gsim
    state: directory

- file:
    dest: ~/project/build/assembly/fabric
    state: directory

- copy:
    src: fabric_bundle.zip
    dest: ~/project/build/assembly/fabric
    
- copy:
    src: docker-compose.yml
    dest: ~/project/

- copy:
    src: .env
    dest: ~/project/

- copy:
    src: launch.pb.json
    dest: ~/project/

# TODO: The nodes should probably be tracked in ansible config
- shell: cd ~/project && docker-compose config --services 2>/dev/null | grep fabric
  register: fabric_svcs

- copy:
    src: prometheus.yml
    dest: ~/project/

- template:
    src: scrape_config.yml.j2
    dest: ~/scrape_config.yml
