#!/bin/bash
IMPROBABLE_RECEPTIONIST_HOST="$1"
IMPROBABLE_RECEPTIONIST_PORT="$2"
IMPROBABLE_WORKER_ID="$3"

MONO="mono"
MONO_ARGS=""

if [ "$(uname)" = "Darwin" ] ; then
    MONO_ARGS="--arch=64"
fi

WORKER_CMD="$MONO $MONO_ARGS ./Example.exe --hostname=$IMPROBABLE_RECEPTIONIST_HOST --port=$IMPROBABLE_RECEPTIONIST_PORT --worker-id=$IMPROBABLE_WORKER_ID"

$WORKER_CMD
