---
- hosts: all
  roles:
    - { role: base, tags: "base" }
    - { role: docker, tags: "docker" }
    - { role: docker_client, tags: "docker_client" }
    - { role: fabric, tags: "fabric" }

- hosts: manager
  roles:
    - { role: docker_registry, tags: "docker_registry", when: not gcloud_docker }
